### ISSUE TITLE
Custom background colors?

### ISSUE THREAD

**Issue by itsjustmath** [itsjustmath/roam-matrix#1]
```css
/*
  Custom background colors 

  Colors borrowed from Priority Matrix app
*/

.kanban-board .kanban-column:nth-child(1) {
  background-color: rgba(255, 234, 229, 0.5);
}

.kanban-board .kanban-column:nth-child(2) {
  background-color: rgba(239, 242, 222, 0.5);
}

.kanban-board .kanban-column:nth-child(3) {
  background-color: rgba(226, 242, 254, 0.5);
}

.kanban-board .kanban-column:nth-child(4) {
  background-color: rgba(240, 240, 240, 0.5);
}
```
